### ISSUE TITLE
"TaskbarXIMFCGUI.exe" does not Run

### ISSUE THREAD

**Issue by Tomasvgamer11** [ChrisAnd1998/TaskbarXI#121]
# When running "TaskbarXIMFCGUI.exe" an error pops-up:
![Error](https://user-images.githubusercontent.com/107812531/182048108-0bdfbe4a-2cb7-4b90-81c8-085316156198.png)
*Translation:* "The Code Execution cannot proceed because mfc140u.dll was not found. Reinstalling the Program may fix this problem"

I have the DLL File installed but it does not work anyways.

# Information:
-PC Edition: Windows 11 Home
-PC Version: 21H2
-Program Version: 1.0.4.0

**Comment by L1ghtingBolt** [comment]
Same problem, why was it closed?

**Comment by alihamza02** [comment]
Same problem. Downloaded the .dll file too. Kindly @Tomasvgamer11 tell us the solution.
