### ISSUE TITLE
TaskbarXI shows full taskbar when the window is full sized

### ISSUE THREAD

**Issue by Ali-Milani-13** [ChrisAnd1998/TaskbarXI#140]
Hello dear developer.
as you can see when you full scale the app, it shows the original taskbar on Windows 11. 
![image](https://user-images.githubusercontent.com/101967444/206910670-cec5f382-6585-4cf9-a700-5632c40942d2.png)

**Comment by sealevelcain** [comment]
![image](https://user-images.githubusercontent.com/30099571/207018413-c321426b-08a1-482d-a745-7765d798669b.png)


You have to enable the 'Ignore max' option in the config window to prevent this behaviour.

**Comment by Ali-Milani-13** [comment]
Thank you for help. that's the solution
