### ISSUE TITLE
Bug report: Double tray overflow chevron when there are notifications

### ISSUE THREAD

**Issue by andiemmadavies** [ChrisAnd1998/TaskbarXI#15]
Whenever the blue notification count badge is shown on Windows 11, there's an additional chevron icon displayed where there shouldn't be one, shown in the screenshot below to overlap the network status icon:

![Screenshot](https://user-images.githubusercontent.com/17612522/136771297-7cef04e4-7a7b-43dd-9884-ad454abaceed.png)

**Comment by ChrisAnd1998** [comment]
At first i stripped down TaskbarX for Windows 11 but i decided to start fresh in C++. So at this moment the bug should be gone.

**Comment by andiemmadavies** [comment]
Ah, great to see you're continuing development into W11, @ChrisAnd1998! Thanks for the bugfix, I'll try this out again soon and keep my eye open for any other issues 👍
