### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [ChrisAnd1998/TaskbarXI#168]
title

**Comment by blinx-ved** [comment]
https://github.com/TaskbarXI/TaskbarXI

**Comment by yuri-becker** [comment]
> TaskbarXI/TaskbarXI

Be careful, its a trojan.

**Comment by blinx-ved** [comment]
It is? How do you know?

**Comment by yuri-becker** [comment]
> It is? How do you know?

My antivirus blocked some suspicious behaviour after i ran it, uploaded it to virustotal: https://www.virustotal.com/gui/file/b91350fa8d67b9989af8005bca5ecf550e1469691ffd22ac754bc8e6d4476e9c/behavior

**Comment by ChrisAnd1998** [comment]
The project is not dead and also not a trojan....

**Comment by yuri-becker** [comment]
> The project is not dead and also not a trojan....

Yea, i didnt mean this project but the fork linked by @blinx-ved .
