### ISSUE TITLE
Janky animation

### ISSUE THREAD

**Issue by RealMistakd** [ChrisAnd1998/TaskbarXI#22]
I like that the taskbar goes back to the full length when you open a window (i think showing the desktop when a window is maximized would look pretty weird) but I suggest adding a smoother animation when the taskbar goes back to normal. It is a bit janky rn with the taskbar kind of snapping back to normal. Otherwise this is a fantastic little tool and I defiantly prefer this over the normal taskbar. Keep it up! 👍

**Comment by RealMistakd** [comment]
Oh one more thing i forgot to mention is that it looks like the taskbar height is slightly shorter than the height when a window is maximized. I would just adjust that to match. :)

**Comment by ChrisAnd1998** [comment]
@RealMistakd I will see if i can get it to change smoothly ;). I actually made it shorter because there is a little dark line on top of the taskbar. When i add taskbar styling support in the future you will see that line.

**Comment by RealMistakd** [comment]
>

**Comment by RealMistakd** [comment]
oops didnt mean to close it lol. thanks for responding :).
