### ISSUE TITLE
Suggestion: Add an option to group the system tray with the taskbar instead of leaving it at the right

### ISSUE THREAD

**Issue by tantalising** [ChrisAnd1998/TaskbarXI#24]
This will probably result in better experience where a user will not have to take their cursor all the way to the right for icons. Reference  [image](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linux.com%2Ftopic%2Fdesktop%2Fdeepin-linux-gorgeous-it-user-friendly%2F&psig=AOvVaw243sypSPPgCqylJ22vvAw5&ust=1641481777043000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCODCzKfymvUCFQAAAAAdAAAAABAD).

**Comment by ChrisAnd1998** [comment]
Currently working on this feature.
Use version 1.0.1.0 with the **-sticky** parameter. It is buggy though... I hope I can get it right!

**Comment by tantalising** [comment]
Just amazing. Thanks for this awesome product. There is some bug like taskbar expanding from edge to edge after making an app fullscreen or the system tray popups are still in the left but I hope this will get eventually fixed. I would to like suggest one another thing. A help parameter. I am closing this and then I will open that as a separate suggestion.

**Comment by ChrisAnd1998** [comment]
@tantalising Thats actually a feature. You can use the **-ignoremax** parameter to disable it ;) A **-help** is a great idea!
