### ISSUE TITLE
T reverting to original when a window is maximized

### ISSUE THREAD

**Issue by anurag-dub3y** [ChrisAnd1998/TaskbarXI#25]
What changes do I need to make in the source code files to stop the taskbar from reverting to full size when a window is maximized?

**Comment by ChrisAnd1998** [comment]
@anurag-dub3y You can download the latest pre-release and use -ignoremax parameter ;)
https://github.com/ChrisAnd1998/TaskbarXI/releases/tag/1.0.1.0

**Comment by ChrisAnd1998** [comment]
![tt](https://user-images.githubusercontent.com/50437199/148356579-df73cad7-afcd-4170-9c7f-44b54080b464.png)

**Comment by anurag-dub3y** [comment]
Thanks @ChrisAnd1998 🤗

**Comment by anurag-dub3y** [comment]
Hey @ChrisAnd1998 I was wondering if you're going to make T transparent at some point, kinda like TranslucentTB and if there's any way I can do it by myself

**Comment by ChrisAnd1998** [comment]
@anurag-dub3y It is on my todo list so it will be possible in a couple days ;)
