### ISSUE TITLE
1.0.1.0 does not start

### ISSUE THREAD

**Issue by 237dmitry** [ChrisAnd1998/TaskbarXI#26]
Errors with `msvcp140.dll` and `vcruntime140.dll`

`VC_redist.x64.exe` was installed. With 1.0.0.0 no problem. `regsvr32.exe` did not solve the problem.

Win 11

**Comment by ChrisAnd1998** [comment]
What about now? I removed all unnecessary includes/imports.

**Comment by 237dmitry** [comment]
> What about now?

The same. Maybe I am doing something wrong. This exe-file is standalone? The 1.0.0.0 was in its environment:
```
Emoji.Wpf.dll
Microsoft.Win32.TaskScheduler.dll
ModernWpf.Controls.dll
ModernWpf.dll
System.dll
System.ValueTuple.dll
TaskbarXI Configurator.application
TaskbarXI Configurator.exe
TaskbarXI Configurator.exe.config
TaskbarXI Configurator.exe.manifest
TaskbarXI Configurator.pdb
TaskbarXI Configurator.xml
TaskbarXI.application
TaskbarXI.exe
TaskbarXI.exe.config
TaskbarXI.exe.manifest
TaskbarXI.pdb
TaskbarXI.xml
Typography.GlyphLayout.dll
Typography.OpenFont.dll
WindowsBase.dll
```
![tbxi](https://user-images.githubusercontent.com/78153320/148369564-576cea25-ba70-4a56-8306-694359cead70.png)

**Comment by ChrisAnd1998** [comment]
@237dmitry ??? Yes remove all those files. And download the latest .exe. I decided to completely start fresh on Windows 11.

**Comment by 237dmitry** [comment]
I had started it as standalone.

**Comment by ilovefreesw** [comment]
Still having this problem in Windows 11 Aindier Build.
![image](https://user-images.githubusercontent.com/77317006/173048263-1bef5963-5a7c-4d34-9e7e-84cfb3bcfa77.png)
