### ISSUE TITLE
[Bug] Icon Clipping 

### ISSUE THREAD

**Issue by PrincessAkira** [ChrisAnd1998/TaskbarXI#30]
![image](https://user-images.githubusercontent.com/45071533/148542173-b722851a-73b8-4420-a75f-0a8be9c30f4d.png)
Only happens if you open the Own app itself e.g its message box and sometimes if u just open another app.
Would it be possible to make the taskbar to extend smoothly in a motion from the small to the bigger state and THEN fade the icon itself in?

**Comment by ChrisAnd1998** [comment]
Should be fixed now! Not sure if that's possible but I will definitely look into that.

**Comment by PrincessAkira** [comment]
> Should be fixed now! Not sure if that's possible but I will definitely look into that.

hmm im running the latest pr. 
or did you not push it yet?

**Comment by PrincessAkira** [comment]
Yes fixed in #7422155c9bdfc0ebac64d5c35b5dc1854e1a1e65
