### ISSUE TITLE
How to launch TaskbarXI with transparent panel?

### ISSUE THREAD

**Issue by 237dmitry** [ChrisAnd1998/TaskbarXI#33]
And so that the taskbar returns to its original state when the window is maximized.
Like it was done in the previous ( .Net ) version:
```powershell
PS > (gps TaskbarXI).CommandLine
"C:\Users\user\bin\tbxi\TaskbarXI.exe" -tbs=1 -color=0;0;0;50 -dtbsowm=1
```

**Comment by ChrisAnd1998** [comment]
Not yet! You can use **-ignoremax** to revert on maximized window.
This only works with the latest pre-release.
https://github.com/ChrisAnd1998/TaskbarXI/releases/tag/1.0.1.0

**Comment by 237dmitry** [comment]
> You can use -ignoremax to revert on maximized window.

No changes: `TaskbarXI -ignoremax -blur` Panel is still blured with maximized window.
