### ISSUE TITLE
Bug: TaskbarXI crashed Windows 11

### ISSUE THREAD

**Issue by Stidon** [ChrisAnd1998/TaskbarXI#37]
Here is the thing: The taskbar when with TaskbarXI is a little buggy (that's what I was gonna report but there is already a report on that) especially when no window is full screen. Out of curiosity, I just restarted explorer.exe to see if it would make thing any better. Then explorer crashed and after that my whole computer crashed and rebooted into safe mode. :(

**Comment by ChrisAnd1998** [comment]
Wow! never had that happen before.

Is this the latest pre-release 1.0.1.0 ?

If yes:
I would like to know your build of Windows 11
Mine is: 22000.376

**Comment by Stidon** [comment]
This was pre-release 1.0.0.0 and yes my Windows 11 build was 22000.376

**Comment by ChrisAnd1998** [comment]
Would you be fine to try out version 1.0.1.0. I have changed a lot that make it run more stable.

**Comment by Stidon** [comment]
Yep, now everything works! Even the buggy animation is gone now. Thanks!

**Comment by ChrisAnd1998** [comment]
Great! Let's hope it keeps running stable now ;)
