### ISSUE TITLE
Order of expand animation

### ISSUE THREAD

**Issue by RealMistakd** [ChrisAnd1998/TaskbarXI#39]
When I open an application that is not pinned the animation looks phenomenal. However when i close that application the animation is exactly the same but reversed. the problem with this is hard to explain with words but basically the taskbar is shrinking before the app can close and the other pinned apps slide in. when opening an unpinned app it looks great because the taskbar scales up first but when it closes the taskbar should scale down after. I didn't look at your code and I don't even know any C++ so idk how hard this will be to accomplish.

**Comment by ChrisAnd1998** [comment]
I understand. However TaskbarXI does/cannot not know when before and after is. It only knows when it happens. What i can do is making the shrinking animation a little slower. On my end it seems to follow the icons nicely now.

**Comment by ChrisAnd1998** [comment]
![22](https://user-images.githubusercontent.com/50437199/148674905-7299401a-d1da-426a-97a1-e9b9c46edde2.jpg)

**Comment by RealMistakd** [comment]
ah. That makes sense. Sounds like a good solution :)

**Comment by ChrisAnd1998** [comment]
I will make this speed adjustable with a setting.
