### ISSUE TITLE
Make TaskbarXI in C#

### ISSUE THREAD

**Issue by itsmeboy0** [ChrisAnd1998/TaskbarXI#4]
Please make TaskbarXI in C# instead of VB.NET. It would be more practical to use and would encourage more contributions ([Microsoft doesn't plan to develop VB.NET further and recommends to move as well](https://www.zdnet.com/article/microsoft-we-wont-evolve-visual-basic-programming-language-but-well-open-it-to-net-5/)).

**Comment by ChrisAnd1998** [comment]
@itsmeboy0 True.. Although I like VB.NET so much more. If I continue with TaskbarXI I might switch to c++

**Comment by andiemmadavies** [comment]
+1, I would be very interested in contributing to coding efforts on this if it was in C#. I would be willing to do the conversion from VB.NET if you'd be interested, @ChrisAnd1998?

**Comment by Mr-Anonymous75** [comment]
> @itsmeboy0 True.. Although I like VB.NET so much more. If I continue with TaskbarXI I might switch to c++

I don't really know VB - but I _definitely_ do know C#, and I'd love to contribute if you decide to switch to it.

**Comment by BirukTes** [comment]
> @itsmeboy0 True.. Although I like VB.NET so much more. If I continue with TaskbarXI I might switch to c++

You will like it, as you dive more, it is getting better, and provides easier way of doing.

**Comment by ChrisAnd1998** [comment]
You may have noticed I decided to do it in C++ just because I want to learn it so badly. I really like how performant it is and that it just doesn't need anything extra to run like .NET Framework.
