### ISSUE TITLE
[BUG] The icon splitting bug is back.

### ISSUE THREAD

**Issue by PrincessAkira** [ChrisAnd1998/TaskbarXI#43]
![image](https://user-images.githubusercontent.com/45071533/148692645-3ff21a94-470a-4d1e-a8e3-6baa85bfa48f.png)

**Comment by PrincessAkira** [comment]
EDIT:

apparently, TaskbarXI crashed in the background and didnt restart the Taskbar itself back to normal.
Should be made, that the Taskbar restores itself back to former. 
This can also be noticed, when quitting the App.

**Comment by ChrisAnd1998** [comment]
Yep, This is caused by the part that checks if the taskbar is already getting animated. I disabled it for now..

**Comment by ChrisAnd1998** [comment]
Allright, now i made so that the application will wait for all animating threads to finish. So this should not happen anymore ;)
