### ISSUE TITLE
How to use TaskbarXI features such as -sticky & -ignoremax

### ISSUE THREAD

**Issue by 2ndSite** [ChrisAnd1998/TaskbarXI#45]
What is the correct syntax in order to apply the features? 
And where to use them
I know this is some lowkey stuff, but i cannot figure it out due to my lack of cmd syntax knowledge, so i thought i might ask

**Comment by jplie** [comment]
Hi, you need to open **powershell** (_win+X_) then type `cd C:\patch\to_folder\with_taskbarXI` and open **TaskbarXI** with your params `./TaskbarXI -sticky -ignoremax`

**Comment by ChrisAnd1998** [comment]
☝️
