### ISSUE TITLE
Can't delete Taskbar XI.exe

### ISSUE THREAD

**Issue by NaraMish** [ChrisAnd1998/TaskbarXI#47]
Please tell me the way to delete the Taskbar XI.exe file as soon as possible.

Thank Bro
![Screenshot (2)](https://user-images.githubusercontent.com/97148348/149165045-41e0da09-407d-401d-a3cb-bfe7b4d63810.png)

**Comment by ChrisAnd1998** [comment]
@NaraMish In the upper right click the arrow icon. Look for the TaskbarXI icon and click on it. Then a messagebox will show up asking if you want to EXIT TaskbarXI. Hit yes. Then delete TaskbarXI.exe.


![149165045-41e0da09-407d-401d-a3cb-bfe7b4d63810](https://user-images.githubusercontent.com/50437199/149168243-c3b28a31-ff23-4c6a-960b-5106ffbc27b2.jpg)

**Comment by Rachel2004** [comment]
I tried this it's not working... please suggest another way
