### ISSUE TITLE
Keep it docked if app is fullscreen

### ISSUE THREAD

**Issue by well-made** [ChrisAnd1998/TaskbarXI#55]
There might be a good reason for it, but whenever I put an App fullscreen, the taskbar because full with / normal again instead of the docked variant.

**Comment by Edmar-Saribay** [comment]
I think they're working on that everyone has the same problem lol. I thought it would be docked when I go into fullscreen too.

**Comment by ChrisAnd1998** [comment]
This is a feature and can be turned off with the **-ignoremax** parameter.
This applies to the latest pre-release 1.0.1.0.
