### ISSUE TITLE
Icons in TaskbarXI missing for Win11

### ISSUE THREAD

**Issue by ezad3280** [ChrisAnd1998/TaskbarXI#63]
Hi @ChrisAnd1998 @PrincessAkira 

FYI. Screenshot attached as a proof regarding the missing icon after I turn on my PC using Windows 11 Pro version 21H2 with OS build 22000.469.

Using TaskbarXI for Windows 11 version 1.0.2.0 purchased from Microsoft Store.

Kindly look into it and fix it soonest possible if you so kind.

Note : I submitted new issue due to my previous issues are closed.

Thanks.

![Screenshot 2022-01-26 174944](https://user-images.githubusercontent.com/98422436/151144088-90f28b97-7d61-4165-bece-1183d3eaf6cf.png)

![Screenshot 2022-01-26 182248](https://user-images.githubusercontent.com/98422436/151146324-e34668ae-6e70-4618-9d50-13ab438ffa48.png)

**Comment by ChrisAnd1998** [comment]
I think I found a fix! It seems to happen randomly. When I am sure it's gone I will push it to the store ;)

**Comment by ezad3280** [comment]
> I think I found a fix! It seems to happen randomly. When I am sure it's gone I will push it to the store ;)

Splendid mate but currently I am using TaskbarX for the transparent gradient style and its worked. Can you push it the styling in TaskbarXI as well. I love the transparent thing for my taskbar. None style is ugly. Hehehehe
