### ISSUE TITLE
Bug: Second monitor's clock doesn't show up when TaskbarXI is activated

### ISSUE THREAD

**Issue by amsyarzero** [ChrisAnd1998/TaskbarXI#82]
Hello! First off, I would like to thank everyone who worked on this program. You all are amazing!

Windows has finally added support for displaying the clock on other displays. However, **when TaskbarXI is activated, the clock on the extra display does not show up**, as shown below:
![after](https://user-images.githubusercontent.com/81513934/156997494-c537dfec-6eed-46d7-a56a-6f9894b424ed.png)

When the taskbar is shown in full though, it appears like normal:
![show up clock](https://user-images.githubusercontent.com/81513934/156997834-e31c72c8-29ad-42a6-a52b-0bb63cd615c5.png)

Thank you in advance!

**Comment by d4kir92** [comment]
yes, i look at the second clock more often then on the main monitor, because main monitor has the game open

would be cool to have same elements on each monitor
