### ISSUE TITLE
[Feature Request] Add MacOS/Linux like bar for clock and wifi

### ISSUE THREAD

**Issue by Jordancjb** [ChrisAnd1998/TaskbarXI#97]
Basically I would love if you added a bar at the top of the screen that looked similar to the menu bar in macos with your clock in the center and some wifi and system tray stuff off to the right, not sure if this is possible I just figured it was because the current taskbarxi version allows for you to move your system traywand. Amazing app!

**Comment by D0naldDank** [comment]
theres a rainmeter skin that does exactly that
its called Droptop
https://github.com/Droptop-Four/Basic-Version

**Comment by Jordancjb** [comment]
> theres a rainmeter skin that does exactly that
> 
> its called Droptop
> 
> https://github.com/Droptop-Four/Basic-Version

Thank you!
